### ISSUE TITLE
Not an issue - excellent work

### ISSUE THREAD

**Issue by biffbaxter** [wakatara/rofi-org-todo#2]
I know - not the right place to put this, but wanted to drop a note - excellent simplicity! Thank you. Hits me right where I need it. i3 - emacs and Rofi user (arch) with thousands of org files and TODO's scattered amongst them all. This lets me keep focused while in an email or something else and to enter a quick task and tags without switching windows or context and risk getting distracted...great, clean and hits the spot. Of course now it makes me want to go hack on Rofi some more. :)

**Comment by wakatara** [comment]
Awww... thank you!   <bows low>

It's actually just really nice to know other people are getting use from this and that it makes their lives better. So, thanks for the kind words.

You would, of course, be the precise target user (I think it also works in sway if you're that way inclined though haven't had time to check it.).

(I'm currently torn between my uber-setup in emacs but getting pressure to move to something more web- and collab-based-- but sooooo much slower 8-/ -- in my new role, but let's see what happens experimenting with Notion and org-oram over next little while. If anything, I find Notion and roam are just giving better ideas on how to re-organize my emacs org-mode more efficienciently... =p ).
